version: '3'

services:
  postgres:
    image: "postgres"
    env_file:
      - ./docker/.env
    ports:
      - "5433:5432"
    volumes:
      - postgre-data:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./docker/start.sh
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - ./docker/.env
    depends_on:
      - postgres
      - redis

  celery:
    build: .
    command: ./docker/worker.sh
    volumes:
      - .:/app/
    env_file:
      - ./docker/.env
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine

volumes:
  postgre-data: { }