# Generated by Django 3.0 on 2022-04-02 10:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("akinator_api", "0003_usergame"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergame",
            name="probabilities",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
