# Generated by Django 3.0 on 2022-04-09 12:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("akinator_api", "0004_usergame_probabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="questions_ids",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
        migrations.AddField(
            model_name="usergame",
            name="questions_ids",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
    ]
