# Generated by Django 3.0 on 2022-04-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akinator_api", "0005_auto_20220409_1235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
