# Generated by Django 3.0 on 2022-04-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akinator_api', '0006_auto_20220409_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
