# Generated by Django 3.0 on 2022-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akinator_api', '0007_usergame_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
