YES_ANSWER = "Yes"
YES_ANSWER_PROBABILITY = 1
NO_ANSWER = "No"
NO_ANSWER_PROBABILITY = 0
DO_NOT_KNOW_ANSWER = "Don't know"
DO_NOT_KNOW_ANSWER_PROBABILITY = 0.5
PROBABLY_ANSWER = "Probably"
PROBABLY_ANSWER_PROBABILITY = 0.75
PROBABLY_NOT_ANSWER = "Probably Not"
PROBABLY_NOT_ANSWER_PROBABILITY = 0.25
ANSWER_CHOICES = [
    (YES_ANSWER_PROBABILITY, YES_ANSWER),
    (NO_ANSWER_PROBABILITY, NO_ANSWER),
    (DO_NOT_KNOW_ANSWER_PROBABILITY, DO_NOT_KNOW_ANSWER),
    (PROBABLY_ANSWER_PROBABILITY, PROBABLY_ANSWER),
    (PROBABLY_NOT_ANSWER_PROBABILITY, PROBABLY_NOT_ANSWER),
]

PROBABILITY_MAPPING = {}
